name: Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run compiler
        working-directory: .
        run: make -f lint.mk
